# Generated by Django 4.2.6 on 2023-12-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='sales',
            field=models.IntegerField(default=0),
        ),
    ]
