# Generated by Django 4.2.6 on 2023-12-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vendor_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold_item',
            field=models.IntegerField(default=0),
        ),
    ]
