# Generated by Django 4.2.6 on 2023-12-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_sold_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_product_sale',
            field=models.IntegerField(default=0),
        ),
    ]
