# Generated by Django 4.2.6 on 2023-12-08 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_total_product_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
    ]
