# Generated by Django 4.2.6 on 2023-12-08 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_product_in_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveredCartOrderProducts',
            fields=[
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.cartorderproducts',),
        ),
    ]
