# Generated by Django 4.2.6 on 2023-12-08 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_deliveredcartorderproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
