# Generated by Django 4.2.6 on 2023-12-08 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_deliveredcartorderproducts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveredCartOrderProducts',
        ),
    ]
