# Generated by Django 4.2.6 on 2023-12-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_filteredcartorderproducts_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartorderproducts',
            options={'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'verbose_name_plural': 'Edit Shop'},
        ),
        migrations.AddField(
            model_name='cartorderproducts',
            name='cancel_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cartorderproducts',
            name='product_status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Processing', 'Order Placed'), ('Preparing', 'Preparing to Ship'), ('Shipped', 'In Transit'), ('Delivered', 'Delivered')], default='Processing', max_length=35),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('rejected', 'Rejected'), ('published', 'Published')], default='in_review', max_length=10),
        ),
    ]
